config/routes.rb
Rails.application.routes.draw do
  post '/login', to:  'sessions#create'
  post '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
  get '/unauthorized', to: 'errors#unauthorized'
  
  
  root 'menu#index'
  resources :postos
  resources :usuarios
  resources :tarefas
  resources :checklists
  resources :roteiros
  resource :session, only: [:new, :create, :destroy]


  get 'usuarios/index'
  get 'postos/index'
  get 'menu/index'
  get 'tarefas/index'
  get 'checklist/index'

end

app/models/tarefa.rb
#class Tarefa < ApplicationRecord
#    has_and_belongs_to_many :checklists
    #has_many :checklist_tarefas
#end

class Tarefa < ApplicationRecord
    has_many :checklist_tarefas, dependent: :nullify
    has_many :checklists, through: :checklist_tarefas
end

app/controllers/tarefas_controller.rb
class TarefasController < ApplicationController
  before_action :require_login
  helper_method :current_user
  
  # GET /tarefas or /tarefas.json
  def index
    @tarefas = Tarefa.all
  end

  # GET /tarefas/1 or /tarefas/1.json
  def show
    @tarefa = Tarefa.find(params[:id])
  end

  # GET /tarefas/new
  def new
    @tarefa = Tarefa.new
  end

  # GET /tarefas/1/edit
  def edit
    @tarefa = Tarefa.find(params[:id])
  end

  # POST /tarefas or /tarefas.json
  def create
    @tarefa = Tarefa.new(tarefa_params)

    respond_to do |format|
      if @tarefa.save
        format.html { redirect_to tarefa_url(@tarefa), notice: "Tarefa was successfully created." }
        format.json { render :show, status: :created, location: @tarefa }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tarefa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tarefas/1 or /tarefas/1.json
  def update
    @tarefa = Tarefa.find(params[:id])
    respond_to do |format|
      if @tarefa.update(tarefa_params)
        format.html { redirect_to tarefa_url(@tarefa), notice: "Tarefa was successfully updated." }
        format.json { render :show, status: :ok, location: @tarefa }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tarefa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tarefas/1 or /tarefas/1.json
  def destroy
    @tarefa = Tarefa.find(params[:id])
    @tarefa.destroy

    respond_to do |format|
      format.html { redirect_to tarefas_url, notice: "Tarefa was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tarefa
      @tarefa = Tarefa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tarefa_params
      params.require(:tarefa).permit(:titulo, :descricao)
    end
end

app/helpers/tarefas_helper.rb
module TarefasHelper
end

app/views/tarefas/_form.html.erb
<%= form_with(model: tarefa) do |form| %>
  <% if tarefa.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tarefa.errors.count, "error") %> prohibited this tarefa from being saved:</h2>

      <ul>
        <% tarefa.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titulo, style: "display: block" %>
    <%= form.text_field :titulo %>
  </div>

  <div>
    <%= form.label :descricao, style: "display: block" %>
    <%= form.text_area :descricao, id: :tarefa_descricao %>
  </div>
    <div class="field">
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tarefas/_tarefa.html.erb
<div id="<%= dom_id tarefa %>">
  <p>
    <strong>Titulo:</strong>
    <%= tarefa.titulo %>
  </p>

  <p>
    <strong>Descricao:</strong>
    <%= tarefa.descricao %>
  </p>

</div>

app/views/tarefas/edit.html.erb
<h1>Editar tarefa</h1>

<%= render "form", tarefa: @tarefa %>

<br>

<div>
  <%= link_to "Show this tarefa", @tarefa %> |
  <%= link_to "Back to tarefas", tarefas_path %>
</div>

app/views/tarefas/index.html.erb
<h1>Tarefas</h1>
<% puts current_user%>
<%= link_to 'Nova Tarefa', new_tarefa_path %>

<table>
  <thead>
    <tr>
      <th>Tarefas</th>
      <th>Opções</th>
    </tr>
  </thead>
  <tbody>
    <% @tarefas.each do |tarefa| %>
      <tr>
        <td><%= tarefa.titulo %></td>
        <td>
          <%= link_to 'Editar', edit_tarefa_path(tarefa) %>
          <%= link_to 'Deletar', tarefa_path(tarefa), method: :delete, data: { confirm: 'Você tem certeza de querer excluir essa tarefa?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tarefas/new.html.erb
<h1>New tarefa</h1>

<%= render "form", tarefa: @tarefa %>

<br>

<div>
  <%= link_to "Back to tarefas", tarefas_path %>
</div>

app/views/tarefas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tarefa %>

<div>
  <%= link_to "Edit this tarefa", edit_tarefa_path(@tarefa) %> |
  <%= link_to "Back to tarefas", tarefas_path %>

  <%= button_to "Destroy this tarefa", @tarefa, method: :delete %>
</div>