config/routes.rb
Rails.application.routes.draw do
  post '/login', to:  'sessions#create'
  post '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
  get '/unauthorized', to: 'errors#unauthorized'
  
  
  root 'menu#index'
  resources :postos
  resources :usuarios
  resources :tarefas
  resources :checklists
  resources :roteiros
  resource :session, only: [:new, :create, :destroy]


  get 'usuarios/index'
  get 'postos/index'
  get 'menu/index'
  get 'tarefas/index'
  get 'checklist/index'

end

app/models/roteiro.rb
class Roteiro < ApplicationRecord
    belongs_to :posto
    has_and_belongs_to_many :usuarios, dependent: :nullify, join_table: :roteiros_usuarios

    accepts_nested_attributes_for :usuarios, allow_destroy: true
end

app/controllers/roteiros_controller.rb
class RoteirosController < ApplicationController
  before_action :require_login
  helper_method :current_user
  
    def index
      @roteiros = Roteiro.all
      @postos = Posto.all
    end
  
    def new
      @roteiro = Roteiro.new
      @usuarios = Usuario.all
      @postos = Posto.all
    end

    def create
      @roteiro = Roteiro.new(roteiro_params)
      @posto = Posto.find(params[:roteiro][:posto_id])
      @roteiro.usuario_ids = params[:roteiro][:usuario_ids].reject!(&:blank?)
      #@roteiro.usuarios = Usuario.where(id: params[:roteiro][:usuario_ids].reject!(&:blank?))

      if @roteiro.save
        @roteiro.usuarios << Usuario.where(id: params[:roteiro][:usuario_ids])
        redirect_to roteiros_path, notice: "Roteiro criado com sucesso!"
      else
        render :new
      end
    end


    def edit
      @roteiro = Roteiro.find(params[:id])
      @posto = @roteiro.posto
      @usuarios_selecionados = @roteiro.usuarios
      @usuarios_disponiveis = Usuario.where.not(id: @usuarios_selecionados.pluck(:id))
    end

    def update
      @roteiro = Roteiro.find(params[:id])
      #adicionar os ids previamente selecionados
      params[:roteiro][:usuario_ids] ||= []
      params[:roteiro][:usuario_ids] += @roteiro.usuario_ids.map(&:to_s)

      if @roteiro.update(roteiro_params)
        redirect_to roteiros_path, notice: "Roteiro Editado com sucesso!!"
      else
        render :edit
      end
    end
    
    def destroy

      @roteiro = Roteiro.find(params[:id])
      @roteiro.destroy

      redirect_to roteiros_path, notice: "Roteiro deletado com sucesso!!"
    end
  
    private
  
    def roteiro_params
      params.require(:roteiro).permit(:nome, :posto_id, usuario_ids:[])
    end
  end

app/helpers/roteiros_helper.rb
module RoteirosHelper
end

app/views/roteiros/_usuario_fields.html.erb
<div>
    <%= f.label :nome %>
    <%= f.text_field :nome %>

    <%= f.hidden_field :_destroy %>
    <%= link_to 'Remove', '#', class: 'remove-fields' %>
<div>

app/views/roteiros/edit.html.erb
<h1>Editar Roteiro</h1>

<%= form_for @roteiro, url: roteiro_path(@roteiro), method: :patch do |form| %>
    <%= form.label :nome %>
    <%= form.text_field :nome %>
<br>
    <%= form.label :posto_id %>
    <%= form.collection_select :posto_id, Posto.all, :id, :cliente, selected: @posto.id %>
<br>
    <%= form.label :usuarios_selecionados, "Usuarios Selecionados" %>
    <%  @usuarios_selecionados.each do |usuario| %>
    <br>
        <%= usuario.nome%><br>
    <% end %>
<br>
    <%= form.label :usuarios_disponiveis, "Usuarios Disponíveis" %>
    <%= form.collection_select :usuario_ids, @usuarios_disponiveis, :id, :nome, {include_hidden: false }, multiple: true, class: 'select2' %>
<br>
    <%= form.submit %>
<% end %>

app/views/roteiros/index.html.erb
<h1>Roteiros</h1>
<% puts current_user%>
<div>
<%= link_to "Novo Roteiro", new_roteiro_path %>
</div>
<table>
    <thead>
        <tr>
            <th>Roteiro</th>
            <th>Posto</th>
        </tr>
    </thead>
    <tbody>
        <% @roteiros.each do |roteiro| %>
            <tr>
                <td><%= roteiro.nome %><% roteiro.inspect %></td>
                <td><%= roteiro.posto.cliente %></td>
                
                <td><%= link_to "Editar", edit_roteiro_path(roteiro) %></td>
                <td><%= link_to 'Deletar', roteiro, method: :delete, data: {confirm: 'Tem certeza que quer excluir o roteiro?' }%></td>
            <tr>
        <% end %>
    </tbody>
</table>

app/views/roteiros/new.html.erb
<h1>Novo Roteiro</h1>

<%= form_with model: @roteiro, url: roteiros_path do |form| %>
  <%= form.label :nome %>
  <%= form.text_field :nome %>
<br>
  <p><%= form.label :usuario %></p>
  <%= form.collection_select :usuario_ids, @usuarios, :id, :nome, { include_hidden: false},  {multiple: true}  %>
 <br> 
  <p><%= form.label :posto %></p>
  <%= form.collection_select(:posto_id, @postos, :id, :cliente, {prompt: "Selecione o Posto"}) %>
<br>
 <br>
  <%= form.submit %>
<% end %>