config/routes.rb
Rails.application.routes.draw do
  post '/login', to:  'sessions#create'
  post '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
  get '/unauthorized', to: 'errors#unauthorized'
  
  
  root 'menu#index'
  resources :postos
  resources :usuarios
  resources :tarefas
  resources :checklists
  resources :roteiros
  resource :session, only: [:new, :create, :destroy]


  get 'usuarios/index'
  get 'postos/index'
  get 'menu/index'
  get 'tarefas/index'
  get 'checklist/index'

end

app/models/posto.rb
class Posto < ApplicationRecord
   has_many :posto_checklists
   has_many :checklists, through: :posto_checklists
   has_many :roteiros
end

app/controllers/postos_controller.rb
class PostosController < ApplicationController
  before_action :require_login
  helper_method :current_user
  
  def index
    @posto = Posto.all
  end
  
  def show
    @posto = Posto.find(params[:id])
  end

  def new
    @posto = Posto.new
    @checklist = Checklist.all
  end

  def create
    @posto = Posto.new(posto_params)

      # You can use the 'checklist_ids' parameter to retrieve the selected checklists from the form
    selected_checklist = Checklist.find(params[:posto][:checklist_ids])

    # You can then add the checklist to te new posto
    #@posto.checklists << selected_checklist
    @posto.checklist_id = params[:posto][:checklist_ids]

    if @posto.save
      redirect_to postos_path, notice:"Posto cadastrado com sucesso!"
    else 
      render :new
    end
  end

  def edit
    @checklist = Checklist.all
    #@posto = Posto.find(params[:id])
    @posto = Posto.includes(:checklists).find(params[:id])

  end

  def update
    @posto = Posto.find(params[:id])
    selected_checklist_ids = params[:posto][:checklist_ids]

    if @posto.update(posto_params)
      @posto.checklists.replace(Checklist.where(id: selected_checklist_ids))
        
      redirect_to postos_path, notice:"Posto Atualizado com sucesso"
    else
      render 'edit'
    end
  end
    
  def destroy
    #puts "Esse e o params[:id]: #{params[:id]}"
    @posto = Posto.find(params[:id])
    #esse codigo abaixo vai fazer uma disassociação com a tabela roteiros
    @posto.roteiros.clear


    if @posto.destroy
      redirect_to postos_path, notice:"Posto deletado com sucesso!"
    else
      redirect_to postos_path, notice: "Erro ao deletar o Posto!"
    end
  end

  private
  def posto_params
    params.require(:posto).permit(:cliente, :checklist_ids)
  end
end

app/helpers/posto_helper.rb
module PostoHelper
end

app/views/postos/edit.html.erb
<h1>Editar Posto</h1>

<%= form_for @posto, url: posto_path(@posto), method: :patch do |f| %>
<%= f.label :cliente%>
<%= f.text_field :cliente %>
<br>
<%= f.label :checklist_id %>
<%= f.collection_select :checklist_ids, Checklist.all, :id, :name, {}%>
<br>
<br>

<%= f.submit "Salvar" %>
<%= link_to "Cancelar", :back %>
<% end %>

app/views/postos/index.html.erb
<h1>Postos </h1>
<%= link_to "Criar Novo Posto", new_posto_path %>
<table>
    <thead>
        <tr>
            <th>Postos</th>
            <th>Opções</th>
    </thead>
    <tbody>
        <% @posto.each do |posto| %>
        <tr>
            <td><%= posto.cliente%></td>
            <td>
                <%= link_to "Editar", edit_posto_path(posto) %>
                <%= link_to "Excluir", posto_path(posto), method: :delete, data:{confirm: "Você tem certeza de querer excluir esse posto?"}%>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>
<br>
<%= link_to "Voltar", :back%>

app/views/postos/new.html.erb
<h1> Cadastro de Postos</h1>
<%= form_with model: @posto, url: postos_path do |f| %>
    <%= f.label :Posto%>
    <%= f.text_field :cliente%>
    <br>
    <%= f.label :checklist_id %>
    <%= f.collection_select :checklist_ids, Checklist.all, :id, :name, prompt: true %>
    <br><br>
    <%= f.submit "Criar Posto" %>
<% end %>
<%= link_to "Cancelar", :back %>

app/views/postos/show.html.erb
<h1>Detalhes Postos </h1>
<%= form_with model: @posto, url: postos_path do |f| %>
    <% f.label :Posto%>
    <% f.text_field :cliente%>
<% end %>
<%= link_to "Voltar", :back%>