config/routes.rb
Rails.application.routes.draw do
  post '/login', to:  'sessions#create'
  post '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
  get '/unauthorized', to: 'errors#unauthorized'
  
  
  root 'menu#index'
  resources :postos
  resources :usuarios
  resources :tarefas
  resources :checklists
  resources :roteiros
  resource :session, only: [:new, :create, :destroy]


  get 'usuarios/index'
  get 'postos/index'
  get 'menu/index'
  get 'tarefas/index'
  get 'checklist/index'

end

app/models/checklist.rb
#class Checklist < ApplicationRecord
#    has_and_belongs_to_many :tarefas
    #has_many :checklist_tarefas, dependent: :destroy
#end

class Checklist < ApplicationRecord
    has_many :posto_checklists
    has_many :checklist_tarefas, dependent: :destroy
    has_many :tarefas, through: :checklist_tarefas
    has_many :postos, through: :posto_checklists 

    before_destroy :cleanup_checklist_tarefas

    def cleanup_checklist_tarefas
        checklist_tarefas.destroy_all
    end

end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
  before_action :require_login
  helper_method :current_user
    def index
        @checklist = Checklist.all
      end

    def show
        @checklist = Checklist.find(params[:id])
      end

    def new
        @checklist = Checklist.new
        @tarefa = Tarefa.all
    end     
      

    def create
        @checklist = Checklist.new(checklist_params)
        @checklist.tarefas = Tarefa.find(params[:checklist][:tarefa_ids].split(","))

        if @checklist.tarefas.empty?
          flash[:error] = "É NECESSÁRIO RESCOLHER PELO MENOS UMA TAREFA!"
          render :new
        else
          if @checklist.save
            tarefa_ids = params[:checklist][:tarefa_ids].split(",")

            tarefa_ids.each do |tarefa_id|
              @checklist.checklist_tarefas.create(tarefa_id: tarefa_id) if tarefa_id.present?
            end

            redirect_to checklists_path, notice: "CHECKLIST CRIADO COM SUCESSO!!"
          else
            render :new
          end
        end
      end

    def edit
        @tarefa = Tarefa.all
        @checklist = Checklist.includes(:tarefas).find(params[:id])
    end

    def update
        @checklist = Checklist.find(params[:id])
        @checklist.tarefas = Tarefa.find(params[:checklist][:tarefa_ids].split(","))

        if @checklist.update(checklist_params)
            redirect_to checklists_path, notice: "Checklist Atualizado com Sucesso"
        else
            render 'edit'
        end
    end

    def destroy
        @checklist = Checklist.find(params[:id])
        #@checklist_tarefas = checklist_tarefas.find(params[:checklist_tarefas])
        ActiveRecord::Base.transaction do
          @checklist.checklist_tarefas.destroy_all 
          @checklist.destroy

        redirect_to checklists_path, notice:"Checklist deletado com sucesso"
    end

  rescue ActiveRecord::InvalidForeignKey
    redirect_to checklists_path, alert: "Não pode se excluído por conta da associação ao banco de dados"
  end

    private
    def checklist_params
        params.require(:checklist).permit(:name, tarefa_ids: [])
    end
end

app/helpers/checklist_helper.rb
module ChecklistHelper
end

app/views/checklists/_checklist.html.erb
<div id="<%= dom_id checklist %>">
<ul>
  <% @checklist.each do |checklist| %>
  <li>
    <%= checklist.name%>
    
  </li>
</ul>
  <p>
    <strong>Titulo:</strong>
    <%= checklist.name %>
  </p>
</div>

app/views/checklists/edit.html.erb
<h1>Editar Checklist</h1>

<%= form_for @checklist, url: checklist_path(@checklist), method: :patch do |f| %>
    <%= f.label :Checklist %>
    <%= f.text_field :name %>
    <br>
    <p>Selecione as atividades a serem efetuadas</p>
    <br>
    <%= f.label :Tarefas %>
    <br>
    <% Tarefa.all.each do |tarefa| %>
        <% checked = @checklist.tarefas.include?(tarefa)%>
        <%= check_box_tag "checklist[tarefa_ids][]", tarefa.id, checked%>
        <%= tarefa.titulo %><br>
    <% end %>
    <br>
    <%= f.submit "Salvar" %>
    <%= link_to "Cancelar", :back  %>
<% end %>

app/views/checklists/index.html.erb
<h1>Checklists</h1>
<% puts current_user%>
<%= link_to "Criar novo Checklist", new_checklist_path %>
<br>
<ul>
  <% @checklist.each do |checklist| %>
    <li>
      <%= checklist.name %>
      <%= link_to "Editar", edit_checklist_path(checklist) %>
      <%= link_to "Excluir", checklist_path(checklist), method: :delete, data:{confirm: "Você tem certeza de que quer apagar?"}%>
    </li>
    <br>
  <% end %>
</ul>
<%= link_to "Voltar", :back %>

app/views/checklists/new.html.erb
<h1>Novo Checklist</h1>

<%= form_with model: @checklist do |f| %>
<div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control" %>
</div>

<div class="form-group">
    <p>Selecione quais tarefas irá realizar! </p>
    <%= f.label :tarefas %><br>
    <% @tarefa.each do |tarefa| %>
        <%= f.check_box :tarefa_ids, {multiple: true }, tarefa.id, nil %>
        <%# check_box_tag "checklist[tarefa_ids]", tarefa.id %>
        <%= tarefa.titulo %><br>
    <% end %>
</div>

<%= f.submit "Criar Checklist", class: "btn btn-primary" %>
<% end %>

app/views/checklists/show.html.erb
<h1>Detalhes Checklist <h1>
<%= form_with model: @checklist, url: checklists_path do |f| %>
    <% f.label :name %>
    <% f.text_field :name %>

    <%= form_with model: @tarefa, url: tarefa_path do |t| %>
        <%t.label :titulo %>
        <% t.text_field :titulo %>
    <% end %>
<% end %>
<%link_to "Voltar", :back %>